### ISSUE TITLE
Some questions for OatmealDome need to answer please

### ISSUE THREAD

**Issue by Fadi5555** [OatmealDome/SplatStages#8]
@OtmealDome hi there

Well. First of all I'm so sorry to tell you something like this here because I didn't find any place to tell you.

But believe me. I'm super fan of your work. Anyway can you tell me what is your progress about Dolphin emu for iOS?
Well we really really want from you to continue your amazing work on it please.
You didn't know how we want this for long time. We all counting on you about it.

The best  and amazing part about it I could install your amazing project on my iPad Air 2. But currently doesn't work I can go on it but it crash after a few seconds (it's good thing as a beginning) you really need to ask people who are familiar of these stuff to help you.

Anyway this is some images for your work (DolphiniOS)
![image](https://cloud.githubusercontent.com/assets/10546081/11451452/d02ede8c-95d7-11e5-976f-3d9fb0303311.png)
![image](https://cloud.githubusercontent.com/assets/10546081/11451454/d088ca28-95d7-11e5-9834-0cedd69110f1.png)
![image](https://cloud.githubusercontent.com/assets/10546081/11451453/d0833f04-95d7-11e5-8479-6dcf4de46386.png)

And this is a repo that I'm taking the emu from it
Williamlcobb.com/repo/

Other thing: I found another dolphin emu on cydia repo but it doesn't install

This is image for that emu
![image](https://cloud.githubusercontent.com/assets/10546081/11451467/71614ad8-95d8-11e5-8d8b-aa48f4448258.png)
 
And this is the repo of this emu
Cydia.myrepospace.com/emulators-galore/

So you as a professional of this stuff can you tell what is this? Also the weird thing is the version of this emu is 6.496.7. means it looks like have a daily updates?

Well this is all my questions and I hope you answer on them.
Thanks again for your hard work.

Finally I'll be always waiting for anything new related to dolphin emu for iOS. This is our dream and I hope you will make it come true.

**Comment by OatmealDome** [comment]
(Just closing this issue because this repository is unrelated to DolphiniOS)

I haven't done any work on DolphiniOS since this summer. Nothing has changed, **it won't run anything**. The closest thing to progress was when I checked to see if iOS 9 changed the way it handles memory. (spoiler: it didn't) 

I'm not sure who WilliamLCobb is, but I assume that he has just compiled my source and put up a package on his repo. I didn't even make that application icon (In my repository, I left it blank so iOS uses the default "no icon" image). About the emulators-galore, I also have no idea who they are and I assume it's a scam since the version number is so high.

I heard that HdkR (a Dolphin dev) "intends on experimenting with Dolphin on iOS once he gets an iPad Pro". I haven't heard anything since, but the iPad Pros are expensive as hell, so I'd understand if it takes a while.

If you want to hear more about why it's so hard to run Dolphin on iOS, [here's a forum post](https://forums.dolphin-emu.org/Thread-ios-port-for-dolphin?pid=390826#pid390826) I typed up earlier.
